"""
archiver.cookies
────────────────
Firefox cookie export utility — read cookies.sqlite from a named profile
and write them as Netscape-format cookies.txt (the format yt-dlp / gallery-dl
expect via --cookies / cookiefile).

Why read sqlite directly:
  No browser extension needed. Firefox stores cookies in a regular SQLite
  database. The catch: Firefox holds an EXCLUSIVE lock on cookies.sqlite
  while it's running. Solution: copy the file first, read the copy, delete.

Why per-domain export:
  We don't dump every cookie in the profile — only the ones for the
  domain(s) you specify. Reduces leakage if cookies.txt is mishandled.

This module is also used by the self-healer: when TikTok auth fails, the
healer calls `refresh_for_domain("tiktok.com", ...)` directly to re-export
fresh cookies and retry.
"""

from __future__ import annotations

import configparser
import logging
import os
import shutil
import sqlite3
import sys
import tempfile
from pathlib import Path

log = logging.getLogger(__name__)

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# Generated by archiver.cookies\n"
    "# This is a generated file!  Do not edit.\n\n"
)


# ── Firefox profile discovery ─────────────────────────────────────────────────

def _firefox_root() -> Path:
    """Return platform-appropriate Firefox application support directory."""
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "Firefox"
    if sys.platform.startswith("linux"):
        return Path.home() / ".mozilla" / "firefox"
    if sys.platform == "win32":
        appdata = os.environ.get("APPDATA")
        if not appdata:
            raise RuntimeError("APPDATA not set; can't locate Firefox profiles.")
        return Path(appdata) / "Mozilla" / "Firefox"
    raise RuntimeError(f"Unsupported platform for Firefox profile lookup: {sys.platform}")


def list_profiles() -> list[tuple[str, Path]]:
    """Return [(profile_name, profile_dir), ...] from profiles.ini."""
    ini_path = _firefox_root() / "profiles.ini"
    if not ini_path.exists():
        return []

    cfg = configparser.ConfigParser()
    cfg.read(ini_path)

    profiles: list[tuple[str, Path]] = []
    for section in cfg.sections():
        if not section.startswith("Profile"):
            continue
        name        = cfg.get(section, "Name",       fallback="unknown")
        path_val    = cfg.get(section, "Path",       fallback=None)
        is_relative = cfg.getboolean(section, "IsRelative", fallback=True)
        if not path_val:
            continue
        full_path = (ini_path.parent / path_val) if is_relative else Path(path_val)
        profiles.append((name, full_path))
    return profiles


def find_profile_by_name(name: str) -> Path:
    """Case-insensitive lookup. Raises RuntimeError if not found."""
    profiles = list_profiles()
    for profile_name, profile_path in profiles:
        if profile_name.lower() == name.lower():
            return profile_path

    available = ", ".join(f'"{n}"' for n, _ in profiles) or "(none)"
    raise RuntimeError(
        f'Firefox profile "{name}" not found. Available: {available}'
    )


# ── Cookie extraction ─────────────────────────────────────────────────────────

def _expiry_seconds(expiry) -> int:
    """Normalize a cookie expiry to whole seconds since the epoch.

    The Netscape cookies.txt format (consumed by yt-dlp/ffmpeg/curl) expects
    seconds, but some browser stores keep this field in milliseconds. Anything
    larger than a plausible second-granularity timestamp (~year 2286) is
    treated as milliseconds and scaled down. A missing/zero value (session
    cookie) is preserved as 0.
    """
    try:
        v = int(expiry)
    except (TypeError, ValueError):
        return 0
    if v <= 0:
        return 0
    # 10-digit seconds top out around year 2286 (1e10); ms timestamps are 13.
    while v > 9_999_999_999:
        v //= 1000
    return v


def _read_cookies(profile_path: Path, domain_filter: str) -> list[dict]:
    """
    Read cookies whose host matches domain_filter (e.g. 'tiktok.com').
    The SQL LIKE pattern is '%<domain_filter>'.
    """
    sqlite_path = profile_path / "cookies.sqlite"
    if not sqlite_path.exists():
        raise RuntimeError(
            f"cookies.sqlite not found in profile: {profile_path}\n"
            "Are you sure this profile has visited the site?"
        )

    # Copy to temp — Firefox holds an exclusive lock on the live file.
    with tempfile.NamedTemporaryFile(suffix=".sqlite", delete=False) as tmp:
        tmp_path = tmp.name
    try:
        shutil.copy2(sqlite_path, tmp_path)
        conn = sqlite3.connect(tmp_path)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            """SELECT host, name, value, path, expiry, isSecure
               FROM moz_cookies WHERE host LIKE ?
               ORDER BY host, name""",
            (f"%{domain_filter}",),
        ).fetchall()
        conn.close()
    finally:
        # Always clean up the temp copy, even on error.
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    cookies = []
    for row in rows:
        host = row["host"]
        # Netscape format: domain must start with '.' for subdomain matching.
        if not host.startswith("."):
            host = "." + host
        cookies.append({
            "domain": host,
            "subdomains": "TRUE",
            "path":   row["path"],
            "secure": "TRUE" if row["isSecure"] else "FALSE",
            "expiry": str(_expiry_seconds(row["expiry"])),
            "name":   row["name"],
            "value":  row["value"],
        })
    return cookies


def _write_netscape(cookies: list[dict], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(NETSCAPE_HEADER)
        for c in cookies:
            f.write("\t".join([
                c["domain"], c["subdomains"], c["path"],
                c["secure"], c["expiry"], c["name"], c["value"],
            ]) + "\n")


# ── Public API ────────────────────────────────────────────────────────────────

def refresh_for_domain(
    domain:       str,
    profile_name: str,
    output_path:  str | Path,
    required_cookies: set[str] | None = None,
) -> int:
    """
    Export cookies for `domain` from Firefox profile `profile_name` to
    `output_path`. Returns the number of cookies written.

    Raises RuntimeError if no cookies found, or if any of the cookies
    in `required_cookies` is missing from the export (likely means the
    user isn't logged in to that profile).
    """
    profile_path = find_profile_by_name(profile_name)
    cookies      = _read_cookies(profile_path, domain)

    if not cookies:
        raise RuntimeError(
            f"No cookies found for domain '{domain}' in profile '{profile_name}'. "
            f"Open {domain} in that Firefox profile and log in, then retry."
        )

    if required_cookies:
        found   = {c["name"] for c in cookies}
        missing = required_cookies - found
        if missing:
            raise RuntimeError(
                f"Critical auth cookies missing from export: {sorted(missing)}. "
                f"Are you logged in to {domain} in profile '{profile_name}'?"
            )

    _write_netscape(cookies, Path(output_path))
    log.info("cookies: exported %d → %s", len(cookies), output_path)
    return len(cookies)
